app = "icf-landipage"
primary_region = "gru"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 4
memory = "1gb"
memory_mb = 8_192
